In [2]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [4]:
df=pd.read_csv("Google_Stock_Price_Train.csv")

In [5]:
df.head(3)

       Date    Open    High     Low   Close     Volume
0  1/3/2012  325.25  332.83  324.97  663.59  7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45  5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21  6,590,300

In [6]:
df.tail(3)

            Date    Open    High     Low   Close     Volume
1255  12/28/2016  793.70  794.23  783.20  785.05  1,153,800
1256  12/29/2016  783.33  785.93  778.92  782.79    744,300
1257  12/30/2016  782.75  782.78  770.41  771.82  1,770,000

In [7]:
training_df=df.iloc[:,1:2].values

In [8]:
training_df

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]], shape=(1258, 1))

In [9]:
sc=MinMaxScaler(feature_range=(0,1))

In [10]:
sc_training_df=sc.fit_transform(training_df)

In [11]:
sc_training_df

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]], shape=(1258, 1))

In [13]:
xtrain=[]
ytrain=[]

In [15]:
for i in range(60,1258):
    xtrain.append(sc_training_df[i-60:i,0])
    ytrain.append(sc_training_df[i,0])

In [16]:
xtrain=np.array(xtrain)

In [17]:
ytrain=np.array(ytrain)

In [18]:
xtrain[0:2]

array([[0.08581368, 0.09701243, 0.09433366, 0.09156187, 0.07984225,
        0.0643277 , 0.0585423 , 0.06568569, 0.06109085, 0.06639259,
        0.0614257 , 0.07474514, 0.02797827, 0.02379269, 0.02409033,
        0.0159238 , 0.01078949, 0.00967334, 0.01642607, 0.02100231,
        0.02280676, 0.02273235, 0.02810849, 0.03212665, 0.0433812 ,
        0.04475779, 0.04790163, 0.0440695 , 0.04648783, 0.04745517,
        0.04873875, 0.03936305, 0.04137213, 0.04034898, 0.04784582,
        0.04325099, 0.04356723, 0.04286033, 0.04602277, 0.05398467,
        0.05738894, 0.05714711, 0.05569611, 0.04421832, 0.04514845,
        0.04605997, 0.04412531, 0.03675869, 0.04486941, 0.05065481,
        0.05214302, 0.05612397, 0.05818885, 0.06540665, 0.06882953,
        0.07243843, 0.07993526, 0.07846566, 0.08034452, 0.08497656],
       [0.09701243, 0.09433366, 0.09156187, 0.07984225, 0.0643277 ,
        0.0585423 , 0.06568569, 0.06109085, 0.06639259, 0.0614257 ,
        0.07474514, 0.02797827, 0.02379269, 0.02409033, 0.0159238 ,
        0.01078949, 0.00967334, 0.01642607, 0.02100231, 0.02280676,
        0.02273235, 0.02810849, 0.03212665, 0.0433812 , 0.04475779,
        0.04790163, 0.0440695 , 0.04648783, 0.04745517, 0.04873875,
        0.03936305, 0.04137213, 0.04034898, 0.04784582, 0.04325099,
        0.04356723, 0.04286033, 0.04602277, 0.05398467, 0.05738894,
        0.05714711, 0.05569611, 0.04421832, 0.04514845, 0.04605997,
        0.04412531, 0.03675869, 0.04486941, 0.05065481, 0.05214302,
        0.05612397, 0.05818885, 0.06540665, 0.06882953, 0.07243843,
        0.07993526, 0.07846566, 0.08034452, 0.08497656, 0.08627874]])

In [19]:
xtrain=np.reshape(xtrain,(xtrain.shape[0],xtrain.shape[1],1))

In [20]:
xtrain[0:2]

array([[[0.08581368],
        [0.09701243],
        [0.09433366],
        [0.09156187],
        [0.07984225],
        [0.0643277 ],
        [0.0585423 ],
        [0.06568569],
        [0.06109085],
        [0.06639259],
        [0.0614257 ],
        [0.07474514],
        [0.02797827],
        [0.02379269],
        [0.02409033],
        [0.0159238 ],
        [0.01078949],
        [0.00967334],
        [0.01642607],
        [0.02100231],
        [0.02280676],
        [0.02273235],
        [0.02810849],
        [0.03212665],
        [0.0433812 ],
        [0.04475779],
        [0.04790163],
        [0.0440695 ],
        [0.04648783],
        [0.04745517],
        [0.04873875],
        [0.03936305],
        [0.04137213],
        [0.04034898],
        [0.04784582],
        [0.04325099],
        [0.04356723],
        [0.04286033],
        [0.04602277],
        [0.05398467],
        [0.05738894],
        [0.05714711],
        [0.05569611],
        [0.04421832],
        [0.04514845],
        [0.04605997],
        [0.04412531],
        [0.03675869],
        [0.04486941],
        [0.05065481],
        [0.05214302],
        [0.05612397],
        [0.05818885],
        [0.06540665],
        [0.06882953],
        [0.07243843],
        [0.07993526],
        [0.07846566],
        [0.08034452],
        [0.08497656]],

       [[0.09701243],
        [0.09433366],
        [0.09156187],
        [0.07984225],
        [0.0643277 ],
        [0.0585423 ],
        [0.06568569],
        [0.06109085],
        [0.06639259],
        [0.0614257 ],
        [0.07474514],
        [0.02797827],
        [0.02379269],
        [0.02409033],
        [0.0159238 ],
        [0.01078949],
        [0.00967334],
        [0.01642607],
        [0.02100231],
        [0.02280676],
        [0.02273235],
        [0.02810849],
        [0.03212665],
        [0.0433812 ],
        [0.04475779],
        [0.04790163],
        [0.0440695 ],
        [0.04648783],
        [0.04745517],
        [0.04873875],
        [0.03936305],
        [0.04137213],
        [0.04034898],
        [0.04784582],
        [0.04325099],
        [0.04356723],
        [0.04286033],
        [0.04602277],
        [0.05398467],
        [0.05738894],
        [0.05714711],
        [0.05569611],
        [0.04421832],
        [0.04514845],
        [0.04605997],
        [0.04412531],
        [0.03675869],
        [0.04486941],
        [0.05065481],
        [0.05214302],
        [0.05612397],
        [0.05818885],
        [0.06540665],
        [0.06882953],
        [0.07243843],
        [0.07993526],
        [0.07846566],
        [0.08034452],
        [0.08497656],
        [0.08627874]]])

In [22]:
recurrent=Sequential()
recurrent.add(LSTM(units=50,return_sequences=True,input_shape=(xtrain.shape[1],1)))
recurrent.add(Dropout(0.2))
recurrent.add(LSTM(units=50,return_sequences=True))
recurrent.add(Dropout(0.2))
recurrent.add(LSTM(units=50,return_sequences=True))
recurrent.add(Dropout(0.2))
recurrent.add(LSTM(units=50))
recurrent.add(Dropout(0.2))
recurrent.add(Dense(units=1))

In [23]:
recurrent.compile(optimizer='adam',loss='mean_squared_error')

In [24]:
recurrent.fit(xtrain,ytrain,epochs=50,batch_size=32)

Epoch 1/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 6s 44ms/step - loss: 0.0387
Epoch 2/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.0079
Epoch 3/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0056
Epoch 4/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0054
Epoch 5/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.0050
Epoch 6/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0049
Epoch 7/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.0050
Epoch 8/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0044
Epoch 9/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0047
Epoch 10/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.0045
Epoch 11/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.0043
Epoch 12/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - loss: 0.0041
Epoch 13/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - loss: 0.0039
Epoch 14/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - loss: 0.0040
Epoch 15/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0038
Epoch 16/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0040
Epoch 17/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - loss: 0.0034
Epoch 18/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0035
Epoch 19/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0039
Epoch 20/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.0037
Epoch 21/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.0037
Epoch 22/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0037
Epoch 23/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0032
Epoch 24/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.0033
Epoch 25/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 41ms/step - loss: 0.0034
Epoch 26/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.0033
Epoch 27/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.0035
Epoch 28/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0033
Epoch 29/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0032
Epoch 30/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0027
Epoch 31/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0029
Epoch 32/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.0026
Epoch 33/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0032
Epoch 34/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0029
Epoch 35/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0027
Epoch 36/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0028
Epoch 37/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0026
Epoch 38/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0026
Epoch 39/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - loss: 0.0025
Epoch 40/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0025
Epoch 41/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0027
Epoch 42/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 3s 42ms/step - loss: 0.0023
Epoch 43/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0025
Epoch 44/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.0023
Epoch 45/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0025
Epoch 46/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0024
Epoch 47/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0024
Epoch 48/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0027
Epoch 49/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0024
Epoch 50/50
38/38 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.0024